language: python
python:
  - "2.7"
notifications:
  irc: "chat.freenode.net#nulecule"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pytest-cov coveralls --use-mirrors
  - pip install pep8 --use-mirrors
before_script:
  - pep8 atomicapp
script:
  python -m pytest -vv tests --cov atomicapp
after_success:
  coveralls
